services:
  source:
    image: mysql:5.7
    ports:
      - 33061:3306
    volumes:
      - type: bind
        source: ./source.cnf
        target: /etc/my.cnf
      - source-data:/www/server/data
    environment:
      - MYSQL_ROOT_PASSWORD=root
  replica:
    image: mysql:5.7
    ports:
      - 33062:3306
    volumes:
      - type: bind
        source: ./replica.cnf
        target: /etc/my.cnf
      - replica-data:/www/server/data
    environment:
      - MYSQL_ROOT_PASSWORD=root

volumes:
  source-data:
  replica-data: