services:
  source:
    image: mysql:5.7
    ports:
      - 33061:3306
    volumes:
      - source-data:/var/lib/mysql
      - ./source.cnf:/etc/my.cnf:ro

  replica:
    image: mysql:5.7
    ports:
      - 33062:3306
    volumes:
      - replica-data:/var/lib/mysql
      - ./replica.cnf:/etc/my.cnf:ro
    depends_on:
      - source

volumes:
  source-data:
  replica-data: