services:
  source:
    image: mysql:5.7
    ports:
      - 33061:3306
    volumes:
      - source-data:/var/lib/mysql
      - type: bind
        source: ./source.cnf
        target: /etc/my.cnf

  replica:
    image: mysql:5.7
    ports:
      - 33062:3306
    volumes:
      - replica-data:/var/lib/mysql
      - type: bind
        source: ./replica.cnf
        target: /etc/my.cnf
    depends_on:
      - source

volumes:
  source-data:
  replica-data: